# Atelier Pandas – Capteurs IoT

Analyse et nettoyage des mesures de capteurs IoT (température, humidité, pression, consommation) avant transmission à un futur système de Machine Learning.

In [1]:
import numpy as np
import pandas as pd

## Partie 1 – Series

**1) Créer une Series contenant 4 températures**

In [2]:
temperatures = pd.Series([21.5, 22.8, 19.4, 23.1])
temperatures

0    21.5
1    22.8
2    19.4
3    23.1
dtype: float64

**2) Afficher son index**

In [3]:
temperatures.index

RangeIndex(start=0, stop=4, step=1)

**3) Afficher la 1ère valeur**

In [4]:
temperatures.iloc[0]

np.float64(21.5)

**4) Afficher la dernière valeur**

In [5]:
temperatures.iloc[-1]

np.float64(23.1)

**5) Créer, de deux façons différentes, une Series de 4 températures avec comme index les heures de mesure 12h, 13h, 14h et 15h**

In [6]:
# 1ère façon : en passant l'index directement
temperatures_heures_1 = pd.Series([21.5, 22.8, 19.4, 23.1], index=["12h", "13h", "14h", "15h"])
temperatures_heures_1

12h    21.5
13h    22.8
14h    19.4
15h    23.1
dtype: float64

In [7]:
# 2e façon : en réaffectant l'index d'une Series existante
temperatures_heures_2 = temperatures.copy()
temperatures_heures_2.index = ["12h", "13h", "14h", "15h"]
temperatures_heures_2

12h    21.5
13h    22.8
14h    19.4
15h    23.1
dtype: float64

**6) Afficher la 1ère et la dernière valeur**

In [8]:
temperatures_heures_1.iloc[0], temperatures_heures_1.iloc[-1]

(np.float64(21.5), np.float64(23.1))

## Partie 2 – DataFrame

**1) Créer et afficher le dataframe df_test à partir du dictionnaire suivant**

In [9]:
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}
df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

**2) Importer le dataset mesures_capteurs.csv dans le dataframe df**

In [10]:
df = pd.read_csv("../data/mesures_capteurs.csv")
df.head()
df = pd.read_

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

**3) Afficher les dimensions de df**

In [11]:
df.shape

(605, 9)